### PR TITLE
Updated to latest piston

### PR DESCRIPTION
**Pull request by bvssvni**

### CODE REVIEW

**Comment by bvssvni** [comment]
There is a breaking change on Rust nightly that requires doc comments on constants in the `deny(missing_docs)` lint. This is fixed in the latest Piston libraries.

**Comment by aochagavia** [comment]
There is something in the new version of the libraries that is causing some "noise" (maybe there is another word to describe this)... You can see the difference below:

Image

I have a very limited understanding of this issue. Could it be related to anti-aliasing?

**Comment by aochagavia** [comment]
(thanks btw :smile: )

**Comment by aochagavia** [comment]
Adding `.samples(8)` to the creation of `WindowSettings` fixed it for me. Did this happen automatically in the previous versions?

**Comment by bvssvni** [comment]
I guess so. Can't remember exactly what was the case in previous versions, but samples should be 0 by default now.

**Comment by aochagavia** [comment]
Good to know! Thanks!

**Pull request merged**
