### PR TITLE
Changed OpenGL version to 2.1 to support older hardware

### PR DESCRIPTION
**Pull request by MightyPork**

### CODE REVIEW

**Comment by aochagavia** [comment]
Awesome, thanks!

**Comment by MightyPork** [comment]
Also the `.samples(8)` causes problems, not sure what about that… Removing the line will make it look worse on better graphics, I guess

**Comment by aochagavia** [comment]
Maybe we could have a fallback... If creating the window fails, we try to create it again without sampling instead of just crashing. What do you think of this approach?

**Comment by MightyPork** [comment]
Just spent an hour trying to figure it out. When we call `.into()`, there's a panic caused by `.unwrap()` on an `Err` `Result` somewhere in the Glutin window "constructor"... I tried hacking the files in `~/.cargo`, but it just ignore the changes or re-downloads the package, so that's not the way.

Let me know if you find a solution—it seems panic can't be caught, and it doesn't happen until the `.into()` is called (I tried separating it from the rest).

**Comment by aochagavia** [comment]
Maybe we could switch to the `build` method described [here](http://docs.piston.rs/piston_window/piston/window/struct.WindowSettings.html#method.build). I am not sure if this requires switching to a newer version of Piston though... I don't have time to try it now, but feel free to explore this option if you want :wink:

**Comment by aochagavia** [comment]
I have fixed it! You can take a look at https://github.com/aochagavia/rocket/commit/cfd6d8e3a04938fe47c4ff7c8d4f6b94e577d59f if you want to know the details. Thanks again for your PR!

**Comment by MightyPork** [comment]
nice! I tried upgrading, too, but it all blew up. Have to learn how to use Cargo right. 
Cheers!

**Pull request merged**
