### PR TITLE
Update dependencies and remove FreeType Dependancy

### PR DESCRIPTION
**Pull request by johnthagen**
Confirmed builds and executes on Windows 10 with only SDL2 dependency on stable Rust 0.12.0.

Fun game! :grinning:

### CODE REVIEW

**Comment by aochagavia** [comment]
Awesome! Thanks for these changes and the other pull requests.

I have been thinking about the SDL2 dependency. Originally, we used `pistoncore-glutin_window` but at one point someone added joystick control support, which required SDL2. Now I see that the SDL2 dependency is the only thing that keeps us from being able to `cargo run --release` without any other setup. Therefore I think it would be good to remove it, even though that means we no longer have joystick control support. Do you have any opinion on this? Would you like to implement that on top of this PR? Otherwise I can do it myself.

**Comment by aochagavia** [comment]
(one of the reasons of my comment above is that right now I haven't been able to build your branch because of linking problems caused by SDL)

**Comment by johnthagen** [comment]
I agree that the SDL2 dependency should be removed from this project.  Given that one of the main purposes is to be an example, removing barriers towards building should be a high priority.

My [fledgling piston game](https://github.com/johnthagen/rust-belt) actually does require SDL2 and SDL2_mixer, but that is only because I've added a music soundtrack.

I am not familiar with using SDL2 directly or exactly how you've used the joystick (neither of those I've done yet), so I would suggest this PR be merged in separately, and then have you perform the surgical removing of SDL2.

**Comment by aochagavia** [comment]
OK! I just merged it from the command line, since it needed a rebase after merging your other PRs. Thanks again!

**Pull request closed without merging**
