### PR TITLE
Format code

### PR DESCRIPTION
**Pull request by johnthagen**
This PR runs the `intellij-rust` formatter to make code style consistent* with the [Rust style guide](https://aturon.github.io/).

*Line wrapping on width 99 was not performed in this PR. @aochagavia, any interest in wrapping at 99? I think it could make rocket a little bit easier for others to use as a reference. I'm happy to add it to the PR.

### CODE REVIEW

**Comment by aochagavia** [comment]
I am not sure about this. While some of the changes seem right, there are many details that I think are wrong. Particularly, I don't like that `-42` becomes `- 42` and that the code blocks introduced to shorten lifetimes get indented.

**Comment by johnthagen** [comment]
+1 that negative numbers shouldn't be getting spaces, that definitely should not be happening. I'll probably report a bug to `intellij-rust` about that.

As for the code blocks to shorten lifetimes, I've always seen blocks like these indented: https://doc.rust-lang.org/book/lifetimes.html#thinking-in-scopes

But if you'd like I can revert that part of the format fix as well.

**Comment by aochagavia** [comment]
On a second thought, I think I can live with all the changes except the negative numbers. So I will be happy to merge if you revert that part of the formatting.

**Comment by johnthagen** [comment]
@aochagavia Should be good to go now. And doubled checked about the unary minus operator and you were correct: https://github.com/rust-lang-nursery/fmt-rfcs/issues/45

**Comment by aochagavia** [comment]
Awesome! Thanks!

**Pull request merged**
