### PR TITLE
Add AppVeyor Windows CI build

### PR DESCRIPTION
**Pull request by johnthagen**
Adds Windows CI Build.

@aochagavia Please enable AppVeyor for this project before merging at: https://ci.appveyor.com/project/aochagavia/rocket

### CODE REVIEW

**Comment by johnthagen** [comment]
The Travis failure is unrelated. Seems to a bug ([reported](https://github.com/PistonDevelopers/gfx_graphics/issues/317)) in the graphics backend with the new Beta released today.

**Comment by aochagavia** [comment]
Could you do a `cargo update` as suggested in the issue you linked? It seems like that should fix the Travis failure.

**Comment by aochagavia** [comment]
Thanks!

**Comment by johnthagen** [comment]
@aochagavia Could you enable AppVeyor for this project?https://ci.appveyor.com/project/aochagavia/rocket

**Comment by aochagavia** [comment]
Oops... Thanks for the heads up! I just added a badge to the readme as well :)

**Pull request merged**
