### PR TITLE
Port rocket from Piston to ggez

### LINKED ISSUE #28: Switch to GraphicsTree piston2d backend when it is ready
Each time we draw an entity, Piston executes a draw call to the graphics card. This is incredibly expensive, but it can go unnoticed because the game does not have a big amount of entities. However, if we want others to learn from this project, it would be useful to use a backend that is able to scale. Fortunately, the [graphics_tree](https://github.com/PistonDevelopers/graphics_tree) backend seems to do exactly that, because it batches up the calls to draw and groups them together before sending them to the graphics card.

### LINKED ISSUE #69: errors running `cargo run --release`
Hi there, I'm attempting to run `cargo run --release` and I'm running into 19 errors which are all similar to:

```
error: type `private::ffi::CGSRegionObject` is private
  --> /Users/<user>/.cargo/registry/src/github.com-1ecc6299db9ec823/core-graphics-0.3.2/src/private.rs:81:21
   |
81 |             assert!(ffi::CGSSetSurfaceShape(self.context_id,
   |
```

I'm running `rustc 1.22.1` and I'm on `macOS 10.12.6`. Any idea what could be causing this issue?

### PR DESCRIPTION
**Pull request by acheronfail**
Just putting this here early to have a better place to communicate about it. When this is merged we can close #69.

This could also close #28 as well? Since we're no longer using Piston.

### CODE REVIEW

**Comment by acheronfail** [comment]
Just pushed some changes. I've asked the author of `ggez` if there's a way to create a circle using `SpriteBatch`, so hopefully we can find out an easy way of doing that.

I also found that sometimes enemies would spawn on top of or really close to the player, so I made some minor changes to the calculation logic in the time controller there, now they're always moved to the edge of the `PLAYER_GRACE_AREA`'s circle.

I'll do some testing of it on some other platforms, then we should be good to merge!
At some stage I'll also make it depend on a specific commit of `ggez` too, until they make another release.

**Comment by aochagavia** [comment]
Since using the `--release` flag solves the performance problem completely and `SpriteBatch` is no longer needed, I would suggest removing it. Besides this, I think there are no other issues that need to be addressed in the port to ggez, so if you squash the commits afterwards I will happily merge!

Regarding a high score and speeding up enemies, I would prefer to discuss that in an issue, so feel free to open one.

**Comment by aochagavia** [comment]
Hmmm I think we will also need to update the readme. It should probably link to the repository containing the [SDL2 bindings](https://github.com/Rust-SDL2/rust-sdl2), since it has very detailed instructions on how to install SDL2 on different platforms.

**Comment by acheronfail** [comment]
> Since using the --release flag solves the performance problem completely and SpriteBatch is no longer needed, I would suggest removing it.

So after some testing without `SpriteBatch` there is some minor lag when trying to draw 5+ explosions at once, but I'm not sure that's a big concern.

I've squashed all the commits, and you can merge this whenever you'd like 👌 
Thanks for letting me port it over! 😄

**Comment by aochagavia** [comment]
Great, thanks!

**Pull request merged**
